externalUrl: "localhost"
serveAddr: "0.0.0.0"
servePort: "8080"
maxFileSize: 838860800
stream:
  turnServerAddr: "stun.l.google.com:19302"
  rtcpPLIInterval: 3
  uploadDest: "./upload/"
  extAllowList:
    - "mp4"
  signalPort: "8082"
  rtpReceivePort: "8084"
utils:
  useCompress: false
