version: "3"

services:

        sorrylinus-again:
                build: .
                container_name: sorrylinus-again
                ports:  
                        - "8000:8000/tcp"
                        - "8002:8002/tcp"
                        - "8004:8004/tcp"
                        - "8006:8006/udp"
                        - "31000-31100:31000-31100/udp"
                tty: true
                restart: always